#############################################################################
# Generated by PAGE version 7.5
#  in conjunction with Tcl version 8.6
#  Oct 29, 2022 06:38:27 PM IST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) black
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Absolute
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m46" -background #eff7ff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 600x600+360+8
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1284 701
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    set toptitle "SJ Catalog Generator"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "mainWindow" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    ttk::label $top.tLa49 \
        -background #eff7ff -foreground $vTcl(actual_gui_fg) \
        -font {-family Arial -size 14 -weight bold -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor center -justify center \
        -text {Sweety Jewellers Catalog Generator} -compound left 
    vTcl:DefineAlias "$top.tLa49" "lblHeading" vTcl:WidgetProc "mainWindow" 1
    vTcl:copy_lock $top.tLa49
    ttk::style configure TFrame -background $vTcl(actual_gui_bg)
    ttk::frame $top.tFr57 \
        -borderwidth 2 -relief groove -width 575 -height 45 
    vTcl:DefineAlias "$top.tFr57" "frameMainXLSX" vTcl:WidgetProc "mainWindow" 1
    set site_3_0 $top.tFr57
    ttk::entry $site_3_0.tEn60 \
        \
        -font {-family Arial -size 9 -weight normal -slant roman -underline 0 -overstrike 0} \
        -state readonly -foreground {} -background {} -takefocus {} \
        -cursor {} 
    vTcl:DefineAlias "$site_3_0.tEn60" "entryMainXLSXPath" vTcl:WidgetProc "mainWindow" 1
    vTcl:copy_lock $site_3_0.tEn60
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_3_0.tBu61 \
        -takefocus {} -text {Load Main XLSX} -compound left 
    vTcl:DefineAlias "$site_3_0.tBu61" "btnLoadMainXLSX" vTcl:WidgetProc "mainWindow" 1
    vTcl:copy_lock $site_3_0.tBu61
    place $site_3_0.tEn60 \
        -in $site_3_0 -x 0 -relx 0.017 -y 0 -rely 0.2 -width 410 -relwidth 0 \
        -height 0 -relheight 0.6 -anchor nw -bordermode ignore 
    place $site_3_0.tBu61 \
        -in $site_3_0 -x 0 -relx 0.733 -y 0 -rely 0.2 -width 145 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    vTcl:copy_lock $top.tFr57
    ttk::style configure TFrame -background $vTcl(actual_gui_bg)
    ttk::frame $top.tFr65 \
        -borderwidth 2 -relief groove -width 575 -height 45 
    vTcl:DefineAlias "$top.tFr65" "framePriceCols" vTcl:WidgetProc "mainWindow" 1
    set site_3_0 $top.tFr65
    ttk::entry $site_3_0.tEn60 \
        \
        -font {-family Arial -size 9 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground {} -background {} -takefocus {} -cursor {} 
    vTcl:DefineAlias "$site_3_0.tEn60" "entryPriceCols" vTcl:WidgetProc "mainWindow" 1
    vTcl:copy_lock $site_3_0.tEn60
    ttk::label $site_3_0.tLa77 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor e -justify left \
        -text {Price Columns:} -compound left 
    vTcl:DefineAlias "$site_3_0.tLa77" "lblPriceCols" vTcl:WidgetProc "mainWindow" 1
    vTcl:copy_lock $site_3_0.tLa77
    ttk::label $site_3_0.tLa78 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor e -justify left \
        -text {Labels Per Line:} -compound left 
    vTcl:DefineAlias "$site_3_0.tLa78" "lblLabelsPerLine" vTcl:WidgetProc "mainWindow" 1
    vTcl:copy_lock $site_3_0.tLa78
    ttk::entry $site_3_0.tEn79 \
        \
        -font {-family Arial -size 9 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground {} -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$site_3_0.tEn79" "entryLabelsPerLine" vTcl:WidgetProc "mainWindow" 1
    vTcl:copy_lock $site_3_0.tEn79
    place $site_3_0.tEn60 \
        -in $site_3_0 -x 0 -relx 0.172 -y 0 -rely 0.204 -width 0 \
        -relwidth 0.569 -height 0 -relheight 0.612 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tLa77 \
        -in $site_3_0 -x 0 -relx 0.017 -y 0 -rely 0.204 -width 0 \
        -relwidth 0.147 -height 0 -relheight 0.612 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tLa78 \
        -in $site_3_0 -x 0 -relx 0.75 -y 0 -rely 0.204 -width 0 \
        -relwidth 0.155 -height 0 -relheight 0.612 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tEn79 \
        -in $site_3_0 -x 0 -relx 0.914 -y 0 -rely 0.204 -width 0 \
        -relwidth 0.069 -height 0 -relheight 0.612 -anchor nw \
        -bordermode ignore 
    vTcl:copy_lock $top.tFr65
    ttk::style configure TFrame -background $vTcl(actual_gui_bg)
    ttk::frame $top.tFr82 \
        -borderwidth 2 -relief groove -width 575 -height 45 
    vTcl:DefineAlias "$top.tFr82" "frameButtons" vTcl:WidgetProc "mainWindow" 1
    set site_3_0 $top.tFr82
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_3_0.tBu83 \
        -takefocus {} -text {Generate JPGs} -compound left 
    vTcl:DefineAlias "$site_3_0.tBu83" "btnGenJPG" vTcl:WidgetProc "mainWindow" 1
    vTcl:copy_lock $site_3_0.tBu83
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_3_0.tBu84 \
        -takefocus {} -text {Generate PDF} -compound left 
    vTcl:DefineAlias "$site_3_0.tBu84" "btnGenPDF" vTcl:WidgetProc "mainWindow" 1
    vTcl:copy_lock $site_3_0.tBu84
    place $site_3_0.tBu83 \
        -in $site_3_0 -x 10 -y 10 -width 275 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu84 \
        -in $site_3_0 -x 290 -y 10 -width 275 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    vTcl:copy_lock $top.tFr82
    vTcl::widgets::ttk::scrolledtext::CreateCmd $top.scr85 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 75 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 125 
    vTcl:DefineAlias "$top.scr85" "scrolltxtStdOut" vTcl:WidgetProc "mainWindow" 1

    $top.scr85.01 configure -background white \
        -font "-family {Consolas} -size 9" \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -wrap none
    vTcl:copy_lock $top.scr85
    ttk::style configure TFrame -background $vTcl(actual_gui_bg)
    ttk::frame $top.tFr46 \
        -borderwidth 2 -relief groove -width 575 -height 45 
    vTcl:DefineAlias "$top.tFr46" "framePurchaseXLSX" vTcl:WidgetProc "mainWindow" 1
    set site_3_0 $top.tFr46
    ttk::entry $site_3_0.tEn60 \
        \
        -font {-family Arial -size 9 -weight normal -slant roman -underline 0 -overstrike 0} \
        -state readonly -foreground {} -background {} -takefocus {} \
        -cursor {} 
    vTcl:DefineAlias "$site_3_0.tEn60" "entryPurchaseXLSXPath" vTcl:WidgetProc "mainWindow" 1
    vTcl:copy_lock $site_3_0.tEn60
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_3_0.tBu61 \
        -takefocus {} -text {Load Pur. Order XLSX} -compound left 
    vTcl:DefineAlias "$site_3_0.tBu61" "btnLoadPurchaseXLSX" vTcl:WidgetProc "mainWindow" 1
    vTcl:copy_lock $site_3_0.tBu61
    place $site_3_0.tEn60 \
        -in $site_3_0 -x 0 -relx 0.017 -y 0 -rely 0.2 -width 410 -relwidth 0 \
        -height 0 -relheight 0.6 -anchor nw -bordermode ignore 
    place $site_3_0.tBu61 \
        -in $site_3_0 -x 0 -relx 0.733 -y 0 -rely 0.2 -width 145 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    vTcl:copy_lock $top.tFr46
    ttk::style configure TFrame -background $vTcl(actual_gui_bg)
    ttk::frame $top.tFr48 \
        -borderwidth 2 -relief groove -width 575 -height 45 
    vTcl:DefineAlias "$top.tFr48" "frameImagesFolder" vTcl:WidgetProc "mainWindow" 1
    set site_3_0 $top.tFr48
    ttk::entry $site_3_0.tEn60 \
        \
        -font {-family Arial -size 11 -weight normal -slant roman -underline 0 -overstrike 0} \
        -state readonly -foreground {} -background {} -takefocus {} \
        -cursor ibeam 
    vTcl:DefineAlias "$site_3_0.tEn60" "entryImagesFolder" vTcl:WidgetProc "mainWindow" 1
    vTcl:copy_lock $site_3_0.tEn60
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_3_0.tBu63 \
        -takefocus {} -text ... -compound left 
    vTcl:DefineAlias "$site_3_0.tBu63" "btnSelectImagesFolder" vTcl:WidgetProc "mainWindow" 1
    vTcl:copy_lock $site_3_0.tBu63
    ttk::label $site_3_0.tLa80 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor e -justify left \
        -text {Images Folder:} -compound left 
    vTcl:DefineAlias "$site_3_0.tLa80" "lblImagesFolder" vTcl:WidgetProc "mainWindow" 1
    vTcl:copy_lock $site_3_0.tLa80
    place $site_3_0.tEn60 \
        -in $site_3_0 -x 95 -y 10 -width 430 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu63 \
        -in $site_3_0 -x 530 -y 10 -width 40 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa80 \
        -in $site_3_0 -x 0 -relx 0.017 -y 0 -rely 0.208 -width 0 \
        -relwidth 0.139 -height 0 -relheight 0.625 -anchor nw \
        -bordermode ignore 
    vTcl:copy_lock $top.tFr48
    ttk::style configure TFrame -background $vTcl(actual_gui_bg)
    ttk::frame $top.tFr47 \
        -borderwidth 2 -relief groove -width 575 -height 45 
    vTcl:DefineAlias "$top.tFr47" "frameOutputFolder" vTcl:WidgetProc "mainWindow" 1
    set site_3_0 $top.tFr47
    ttk::entry $site_3_0.tEn60 \
        \
        -font {-family Arial -size 11 -weight normal -slant roman -underline 0 -overstrike 0} \
        -state readonly -foreground {} -background {} -takefocus {} \
        -cursor ibeam 
    vTcl:DefineAlias "$site_3_0.tEn60" "entryOutputFolder" vTcl:WidgetProc "mainWindow" 1
    vTcl:copy_lock $site_3_0.tEn60
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_3_0.tBu63 \
        -takefocus {} -text ... -compound left 
    vTcl:DefineAlias "$site_3_0.tBu63" "btnSelectOutputFolder" vTcl:WidgetProc "mainWindow" 1
    vTcl:copy_lock $site_3_0.tBu63
    ttk::label $site_3_0.tLa80 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor e -justify left \
        -text {Output Folder:} -compound left 
    vTcl:DefineAlias "$site_3_0.tLa80" "lblOutputFolder" vTcl:WidgetProc "mainWindow" 1
    vTcl:copy_lock $site_3_0.tLa80
    place $site_3_0.tEn60 \
        -in $site_3_0 -x 95 -y 10 -width 430 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu63 \
        -in $site_3_0 -x 530 -y 10 -width 40 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa80 \
        -in $site_3_0 -x 0 -relx 0.017 -y 0 -rely 0.208 -width 0 \
        -relwidth 0.139 -height 0 -relheight 0.625 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tLa49 \
        -in $top -x 10 -y 5 -width 580 -relwidth 0 -height 50 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tFr57 \
        -in $top -x 10 -y 60 -width 580 -relwidth 0 -height 50 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tFr65 \
        -in $top -x 10 -y 240 -width 580 -relwidth 0 -height 49 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tFr82 \
        -in $top -x 10 -y 360 -width 580 -relwidth 0 -height 50 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.scr85 \
        -in $top -x 10 -y 420 -width 580 -relwidth 0 -height 170 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tFr46 \
        -in $top -x 10 -y 120 -width 580 -relwidth 0 -height 50 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tFr48 \
        -in $top -x 10 -y 180 -width 580 -relwidth 0 -height 50 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tFr47 \
        -in $top -x 10 -y 300 -width 580 -height 50 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

