#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.5
#  in conjunction with Tcl version 8.6
#    Oct 29, 2022 02:42:27 PM IST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from functions import PrintLogger, ErrorLogger
from tkinter.constants import *

import v3

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = v3.mainWindow(_top1)
    sys.stdout = PrintLogger(_w1.scrolltxtStdOut)
    sys.stderr = ErrorLogger(_w1.scrolltxtStdOut)
    root.mainloop()

if __name__ == '__main__':
    v3.start_up()




